
- name: Restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Restart Server to update network interface"

- name: waiting 30 secs for server to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=60
  become: false
