- name: Create instances
  local_action:
    module: cs_instance
    display_name: "{{ item.name }}"
    template: "{{ item.template }}"
    service_offering: "{{ item.instance_type }}"
    ssh_key: "vpn-gateway-deployment-node"
    security_groups: '{{ item.security_groups }}'
    root_disk_size: '{{ item.root_disk_size }}'
    zone: "{{ item.zone }}"
  with_items: '{{ instances }}'
